formatter: "markdown table"

content: |-
  # AWS RAM module

  This module allows you to share [supported](https://docs.aws.amazon.com/ram/latest/userguide/shareable.html) AWS resources to another accounts or AWS organization
  
  # Example usage:
  ```hcl
  module "aws-ram" {
    source        = "RealArtemiy/ram/aws"
    version       = "~> 1.0"
    name          = "Share Subnets to develop account"
    resource_arns = ["arn:aws:ec2:eu-central-1:123456789101:subnet/subnet-1234567abcd", "arn:aws:ec2:eu-central-1:123456789101:subnet/subnet-abcdef1234"]
    principals    = ["arn:aws:organizations::101987654321:organization/o-abcdef1234", "55555555555"]
    tags = {
      OwnedBy = "network"
    }
  }
  ```
  For organization unit - need to use ARN, but not o-XXXXXXXXXX id, arn can be taken by simply running: `$ aws organizations describe-organization`
  
  Documentation: https://docs.aws.amazon.com/cli/latest/reference/organizations/describe-organization.html
  
  If you wish to share with the principal, accepting the sharing is mandatory. Please see examples.

  {{ .Header }}

  {{ .Providers }}
  
  {{ .Outputs }}
  
  {{ .Inputs }} 

output:
  file: "README.md"
  mode: replace
  template: |-
    {{ .Content }}

sort:
  enabled: true
  by: required